version: '3.9'

services:
  # Mongodb service
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo_data:/data/db
    ports:
      # local->container
      - 27017:27017

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: radiusdb
    depends_on: 
      - mongodb
    links:
      - mongodb

  # Node api service
  freeradius:
    image: freeradius/freeradius-server:latest
    command:  >
      bash -c "set -e;
      echo 'Initialize plugins...';
      chmod 755 /etc/raddb/clients.conf;
      chmod 755 /etc/raddb/mods-available/rest;
      chmod 755 /etc/raddb/sites-enabled/nano;
      chmod 755 /etc/raddb/radiusd.conf;
      echo 'Starting radius server...';
      /docker-entrypoint.sh"
    ports:
      # local->container
      - 1812:1812/udp
      - 1813:1813/udp
    volumes:
      - ./resources/freeradius/clients.conf:/etc/raddb/clients.conf
      - ./resources/freeradius/nano:/etc/raddb/sites-enabled/nano
      - ./resources/freeradius/radiusd.conf:/etc/raddb/radiusd.conf
      - ./resources/freeradius/rest:/etc/raddb/mods-available/rest


