version: '3.9'

services:
  # Mongodb service
  mongodb:
    container_name: db_container
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testing123
    volumes:
      - ./mongo_data:/data/db

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://root:testing123@mongodb:27017
      DB_NAME: radiusdb
    depends_on: 
      - mongodb
    links:
      - mongodb
  # Node api service
  freeradius:
    image: freeradius/freeradius-server:latest
    ports:
      # local->container
      - 1812:1812/udp
      - 1813:1813/udp