version: '3.9'

services:
  # Mongodb service
  mongodb:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      # local->container
      - 27017:27017
  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://127.0.0.1:27017
      DB_NAME: radiusdb
    depends_on: 
      - mongodb
  # Node api service
  freeradius:
    image: freeradius/freeradius-server:latest
    ports:
      # local->container
      - 1812:1812/udp
      - 1813:1813/udp


volumes:
  mongo_data: {}